baseURL = 'https://nethowtos.com/'
languageCode = 'en-us'
title = '.Net HOWTOs'
copyright = "Copyright 2023 Bogdan Novosad"
defaultContentLanguage = "en"
enableGitInfo = true
enableRobotsTXT = true
googleAnalytics = "G-ZNKGKDZ6DL"
# theme = "PaperMod"
[module]
    [[module.imports]]
        path="github.com/adityatelange/hugo-PaperMod"
